#!/bin/sh

set -e

IMAGE_NAME=mender-convert

MENDER_CONVERT_DIR="$(pwd)"
mkdir -p output

docker run \
       --mount type=bind,source=$MENDER_CONVERT_DIR,target=/mender-convert \
       --privileged=true \
       $IMAGE_NAME "$@"
