[Distribution]
Distribution=ubuntu
Release=jammy
RepositoryKeyFetch=true

[Output]
Output=ubuntu-22.04-x86-64.img
OutputDirectory=out
Format=disk

# This will setup multiple items so they not need to be configured manually
[Include]
Include=mkosi-vm

[Content]
Bootable=yes
Bootloader=grub
RootPassword=password
Packages=
    grub-efi-amd64-signed
    shim-signed
    openssh-server
    dhcpcd5
    liblmdb0
    libarchive13
    libboost-log1.74.0
    lsb-release
    apt

[Validation]
Checksum=yes
