#!/bin/sh
# Copyright 2023 Northern.tech AS
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

set -e

if [ -z "$DISK_IMG" ]; then
    echo "ERROR: DISK_IMG is not set"
    exit 1
fi

OS_TYPE=$(cat /etc/os-release | grep "^NAME=" | cut -d= -f2 | tr -d '"')
OS_VERSION=$(cat /etc/os-release | grep "^VERSION_CODENAME=" | cut -d= -f2 | tr -d '"')

echo "Host OS_TYPE: ${OS_TYPE}"
echo "Host OS_VERSION: ${OS_VERSION}"
echo "DISK_IMG: ${DISK_IMG}"

case "${OS_VERSION}" in
    bookworm|jammy)
        echo "Running on legacy Ubuntu / Debian"

        # Look for OVMF_CODE.fd in /usr/share
        OVMF_CODE=$(find /usr/share -type f -and -name OVMF_CODE.fd 2>/dev/null | head -1)
        if [ -z "${OVMF_CODE}" ]; then
            echo "FAILURE: could not find OVMF_CODE file in /usr/share"
            exit 1
        fi

        if [ "$QEMU_NO_SECURE_BOOT" != "1" ]; then
            echo "Secure boot testing"
            VARS=$(dirname "$0")/../../tests/uefi-nvram/OVMF_VARS.fd
            OVMF_VARS="-drive file=${VARS},if=pflash,format=raw,unit=1,readonly=on"
        fi

        echo "OVMF_CODE: ${OVMF_CODE}"
        echo "OVMF_VARS: ${OVMF_VARS}"

        qemu-system-x86_64 \
        -enable-kvm \
        -nographic \
        -m 512 \
        -net user,hostfwd=tcp::${PORT_NUMBER:-8822}-:22 \
        -net nic,macaddr=52:54:00$(od -txC -An -N3 /dev/urandom|tr \  :) \
        -drive file=${OVMF_CODE},if=pflash,format=raw,unit=0,readonly=on \
        $OVMF_VARS \
        -drive format=raw,file=${DISK_IMG} &

        ;;
    *)
        echo "Running on modern Ubuntu / Debian"

        # Look for OVMF_CODE.fd in /usr/share
        # On the Debian 13 and Ubuntu 24.04 OVMF_CODE (2M) has been migrated to OVMF_CODE_4M
        OVMF_CODE=$(find /usr/share -type f -and -name OVMF_CODE_4M.fd 2>/dev/null | head -1)
        if [ -z "${OVMF_CODE}" ]; then
            echo "ERROR: could not find OVMF_CODE_4M file in /usr/share"
            exit 1
        fi

        if [ "$QEMU_NO_SECURE_BOOT" != "1" ]; then
            echo "Secure boot testing"
            # Use legacy vars file
            VARS=$(dirname "$0")/../../tests/uefi-nvram/OVMF_VARS.fd
            OVMF_VARS="-drive file=${VARS},if=pflash,format=raw,unit=1"
            EXTRA_PARAMS="-machine q35,smm=on"
        fi

        echo "OVMF_CODE: ${OVMF_CODE}"
        echo "OVMF_VARS: ${OVMF_VARS}"

        qemu-system-x86_64 \
        -enable-kvm \
        -nographic \
        -m 512 \
        -net user,hostfwd=tcp::${PORT_NUMBER:-8822}-:22 \
        -net nic,macaddr=52:54:00$(od -txC -An -N3 /dev/urandom|tr \  :) \
        -drive file=${OVMF_CODE},if=pflash,format=raw,unit=0,readonly=on \
        $OVMF_VARS \
        -drive format=raw,file=${DISK_IMG} &

        ;;
esac

qemu_pid=$!

trap qemu_cleanup HUP KILL TERM

qemu_cleanup() {
    kill -s TERM $qemu_pid
}

echo "QEMU started with PID $qemu_pid"
wait $qemu_pid
